server:
  port: 8001

#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: qinlinhai
    type: com.alibaba.druid.pool.DruidDataSource
  application:
    name: Emp-instance
#mybatis配置
mybatis:
  type-aliases-package: com.qin.entity
  mapper-locations: classpath:mapper/*.xml